version: '3'
services:
  db:
    image: mongo
    container_name: mongo_db
    restart: always
    volumes:
      - ./mongo:/data/db
    ports:
      - 27017:27017
  app:
    build:
      args:
        TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
        MONGO_DB_URI: ${MONGO_DB_URI}
      context: .
      dockerfile: Dockerfile
    container_name: scheduler
    image: benglish_scheduler
    depends_on:
      - db